version: "3.9"

services:
  django-application: &django
    build:
      context: "./Django"
      dockerfile: "Dockerfile"
      args:
        - PYTHON_VERSION
    hostname: app
    restart: unless-stopped
    env_file:
      - '.env'
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    tty: true
    volumes:
      - static:/app/static  # Map the Django static files directory into the container

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static  # Map the same directory used by Nginx
    ports:
      - "${DOCKER_WEB_PORT:-80}:80"
    depends_on:
      - django-application

volumes:
  static: