version: "3.9"

services:
    django-application-dev:
        extends:
            file: docker-compose.yml
            service: django-application
        container_name: app-dev
        ports:
            - "${DOCKER_WEB_PORT:-8000}:8000"
        build:
            target: dev
        volumes:
            - "./:/app"
        # Force the container to stay alive
        tty: true
