# Generated by Django 5.0.1 on 2024-01-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailystockprices',
            constraint=models.UniqueConstraint(fields=('symbol', 'date'), name='unique_symbol_date'),
        ),
    ]
