# Generated by Django 5.1.5 on 2025-01-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo_finances', '0003_dailystockhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
