# Generated by Django 5.1.5 on 2025-01-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighLow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=100, null=True)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('var_day', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('var_week', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('var_month', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('var_year', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('var_12_months', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('min', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('max', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'High Low',
                'verbose_name_plural': 'High Lows',
            },
        ),
    ]
