# Generated by Django 5.1.5 on 2025-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomoney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlow',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
