# Generated by Django 5.0.1 on 2024-01-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('industry', models.CharField(max_length=255)),
                ('industry_key', models.CharField(max_length=255)),
                ('industry_disp', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('sector_key', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=10)),
                ('quote_type', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('underlying_symbol', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=255)),
                ('long_name', models.CharField(max_length=255)),
                ('first_trade_date_epoch_utc', models.DateTimeField()),
                ('time_zone_full_name', models.CharField(max_length=255)),
                ('time_zone_short_name', models.CharField(max_length=50)),
                ('financial_currency', models.CharField(max_length=10)),
                ('long_business_summary', models.TextField()),
            ],
        ),
    ]
