# Generated by Django 5.0.1 on 2024-01-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo_finances', '0002_company_load_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
                ('dividends', models.DecimalField(decimal_places=6, max_digits=10)),
                ('splits', models.DecimalField(decimal_places=6, max_digits=10)),
                ('load_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
